// Generated by CoffeeScript 1.3.3
/*
# Lorem Ipsum Wrapper
*/

var Lipsum, Parser, Service;

Service = require('./service');

Parser = require('./parser');

Lipsum = (function() {

  function Lipsum() {
    this._parser = new Parser();
    this._service = new Service();
  }

  Lipsum.prototype.getText = function(callback, opts) {
    opts.amount = opts.amount || this._defaults.amount;
    opts.what = opts.what || this._defaults.what;
    return opts.start = opts.start || this._defaults.start;
  };

  Lipsum.prototype._defaults = function() {
    return {
      amount: 5,
      what: 'paras',
      start: 'no'
    };
  };

  return Lipsum;

})();
