// Generated by CoffeeScript 1.3.3
/*
  Web Service for lipsum.org

  author: Travis Kaufman
*/

var Service, http, url;

http = require('http');

url = require('url');

Service = (function() {

  function Service() {}

  Service.prototype.get = function(format, callback, queryOpts) {
    var endpoint, req, urlopts;
    urlopts = {
      protocol: 'http:',
      hostname: 'lipsum.lipsum.com',
      pathname: "/feed/" + format
    };
    if (queryOpts != null) {
      urlopts.query = queryOpts;
    }
    endpoint = url.format(urlopts);
    req = http.request(endpoint, function(res) {
      var payload;
      payload = "";
      res.setEncoding('utf8');
      res.on('data', function(chunk) {
        return payload += chunk;
      });
      return res.on('end', function() {
        return callback(payload);
      });
    }).on('error', function(err) {
      throw new Error(err.message);
    });
    return req.end();
  };

  return Service;

})();

if (typeof module !== "undefined" && module !== null) {
  module.exports = Service;
}
