// Generated by CoffeeScript 1.4.0
/*
  # Web Service for lipsum.com

  Provides the low-level interface to the lipsum.com
  service.
*/

var Service, http, url;

http = require('http');

url = require('url');

Service = (function() {

  function Service() {}

  Service.prototype.get = function(format, callback, queryOpts) {
    /*
        Retrieves the lipsum text.
    
        format: {String} one of "xml" or "json"
    
        callback: {Function} called on successful text retrieval.
                  Should have one parameter to hold the response data.
    
        queryOpts: {Object} options to attach to the query portion of the url.
    */

    var endpoint, req, urlopts;
    urlopts = {
      protocol: 'http:',
      hostname: 'lipsum.com',
      pathname: "/feed/" + format
    };
    if (queryOpts != null) {
      urlopts.query = queryOpts;
    }
    endpoint = url.format(urlopts);
    req = http.request(endpoint, function(res) {
      var payload;
      payload = "";
      res.setEncoding('utf8');
      res.on('data', function(chunk) {
        return payload += chunk.replace(/[\n|\t|\f|\v|\r]+/g, "\\n");
      });
      return res.on('end', function() {
        return callback(payload);
      });
    }).on('error', function(err) {
      throw new Error("Service Error: " + err.message);
    });
    return req.end();
  };

  return Service;

})();

if (typeof module !== "undefined" && module !== null) {
  module.exports = Service;
}
